language: java
jdk: oraclejdk11

before_script: ./script/travis/createPullRequest.sh

deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: gymmappiamoci
  on:
    repo: leafProjects/leaf1

